services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: hut
      POSTGRES_PASSWORD: hut
      POSTGRES_MULTIPLE_DATABASES: metasrht,hubsrht,gitsrht
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres_sh:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    volumes:
      - redis:/data

  meta:
    image: ghcr.io/k8ieone/srht-meta
    build: ./services/meta.sr.ht
    restart: unless-stopped
    ports:
      - 5001:8080
    depends_on:
      - postgres
      - redis
    volumes:
      - ./config/dev/config.ini:/etc/sr.ht/config.ini:ro
      - ./config/dev/email.pub:/etc/sr.ht/email.pub:ro
      - ./config/dev/email.priv:/etc/sr.ht/email.priv:ro

  hub:
    image: ghcr.io/k8ieone/srht-hub
    build: ./services/hub.sr.ht
    restart: unless-stopped
    ports:
      - 5002:8080
      - 5014:5014
    depends_on:
      - postgres
      - redis
    volumes:
      - ./config/dev/config.ini:/etc/sr.ht/config.ini:ro
      - ./config/dev/email.pub:/etc/sr.ht/email.pub:ro
      - ./config/dev/email.priv:/etc/sr.ht/email.priv:ro

  # git:
  #   image: git.sr.ht
  #   build: ./services/git.sr.ht
  #   restart: unless-stopped
  #   ports:
  #     - 5003:8080
  #     - 5022:22
  #   depends_on:
  #     - postgres
  #     - redis
  #   volumes:
  #     - ./config/config.ini:/etc/sr.ht/config.ini:ro
  #     - ./config/email.pub:/etc/sr.ht/email.pub:ro
  #     - ./config/email.priv:/etc/sr.ht/email.priv:ro
      # use ./data/git as a folder to store git repositories
  #     - git:/var/lib/git

volumes:
  git:
  redis:
  postgres:
